import { Category } from '@prisma/client';

export interface SmartphoneData {
  name: string;
  category: Category;
  brand: string;
  price: number;
  stockQuantity: number;
  images: string[];
  description: string;
  ram: number;
  storage: number;
  screenSize: number;
  processor: string;
  color: string;
  os: string;
  releaseYear: number;
  has5G: boolean;
  hasNfc: boolean;
  attributes: Record<string, any>;
}

const smartphones: SmartphoneData[] = [
  // ==================== APPLE (7 моделей) ====================
  {
    name: 'Apple iPhone 16',
    category: Category.SMARTPHONE,
    brand: 'Apple',
    price: 799.99,
    stockQuantity: 40,
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569'],
    description:
      'Base flagship introducing the Action Button, Camera Control, A18 chip built for Apple Intelligence, and vibrant color-infused glass.',
    ram: 8,
    storage: 128,
    screenSize: 6.1,
    processor: 'Apple A18',
    color: 'Ultramarine',
    os: 'iOS',
    releaseYear: 2024,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 3561,
      refreshRate: 60,
      mainCameraMp: 48,
      frontCameraMp: 12,
      bodyMaterial: 'Glass / Aluminum',
      simFormat: 'nanoSIM + eSIM',
    },
  },
  {
    name: 'Apple iPhone 16 Pro Max',
    category: Category.SMARTPHONE,
    brand: 'Apple',
    price: 1199.99,
    stockQuantity: 30,
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569'],
    description:
      'Features a larger 6.9-inch display, Grade 5 Titanium frame, A18 Pro chip, and dedicated Camera Control button.',
    ram: 8,
    storage: 256,
    screenSize: 6.9,
    processor: 'Apple A18 Pro',
    color: 'Desert Titanium',
    os: 'iOS',
    releaseYear: 2024,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 4685,
      refreshRate: 120,
      mainCameraMp: 48,
      frontCameraMp: 12,
      bodyMaterial: 'Titanium',
      simFormat: 'nanoSIM + eSIM',
    },
  },
  {
    name: 'Apple iPhone 17',
    category: Category.SMARTPHONE,
    brand: 'Apple',
    price: 899.99,
    stockQuantity: 35,
    images: ['https://images.unsplash.com/photo-1695048065057-0243e33b6643'],
    description:
      'Standard 2025 iPhone upgraded with 120Hz ProMotion display, A19 chip, and enhanced front TrueDepth camera.',
    ram: 8,
    storage: 256,
    screenSize: 6.3,
    processor: 'Apple A19',
    color: 'Sage Green',
    os: 'iOS',
    releaseYear: 2025,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 3800,
      refreshRate: 120,
      mainCameraMp: 48,
      frontCameraMp: 24,
      bodyMaterial: 'Glass / Aluminum',
      simFormat: 'nanoSIM + eSIM',
    },
  },
  {
    name: 'Apple iPhone 17 Pro',
    category: Category.SMARTPHONE,
    brand: 'Apple',
    price: 1099.99,
    stockQuantity: 35,
    images: ['https://images.unsplash.com/photo-1695048065057-0243e33b6643'],
    description:
      'Powered by the A19 Pro chip with 12GB RAM, 120Hz ProMotion screen, and upgraded 48MP lenses on all rear cameras.',
    ram: 12,
    storage: 256,
    screenSize: 6.3,
    processor: 'Apple A19 Pro',
    color: 'Teal Titanium',
    os: 'iOS',
    releaseYear: 2025,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 4100,
      refreshRate: 120,
      mainCameraMp: 48,
      frontCameraMp: 24,
      bodyMaterial: 'Titanium',
      simFormat: 'eSIM Only / nanoSIM',
    },
  },
  {
    name: 'Apple iPhone SE 4',
    category: Category.SMARTPHONE,
    brand: 'Apple',
    price: 499.99,
    stockQuantity: 50,
    images: ['https://images.unsplash.com/photo-1632661674596-df8be070a5c5'],
    description:
      "Modernized design ditching Home button for All-Screen 6.1 OLED, Face ID, A18 chip, and Apple's custom 5G modem.",
    ram: 8,
    storage: 128,
    screenSize: 6.1,
    processor: 'Apple A18',
    color: 'Starlight',
    os: 'iOS',
    releaseYear: 2026,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 3279,
      refreshRate: 60,
      mainCameraMp: 48,
      frontCameraMp: 12,
      bodyMaterial: 'Glass / Aluminum',
      simFormat: 'eSIM / nanoSIM',
    },
  },
  {
    name: 'Apple iPhone 18 Pro',
    category: Category.SMARTPHONE,
    brand: 'Apple',
    price: 1199.99,
    stockQuantity: 20,
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569'],
    description:
      'Next-gen flagship featuring 2nm A20 Pro SoC, under-display Face ID, and variable mechanical aperture lens.',
    ram: 12,
    storage: 256,
    screenSize: 6.3,
    processor: 'Apple A20 Pro',
    color: 'Deep Titanium',
    os: 'iOS',
    releaseYear: 2026,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 4300,
      refreshRate: 120,
      mainCameraMp: 48,
      frontCameraMp: 24,
      bodyMaterial: 'Titanium',
      simFormat: 'eSIM Only',
    },
  },
  {
    name: 'Apple iPhone Air',
    category: Category.SMARTPHONE,
    brand: 'Apple',
    price: 999.99,
    stockQuantity: 25,
    images: ['https://images.unsplash.com/photo-1632661674596-df8be070a5c5'],
    description:
      'Ultra-thin luxury redesign replacing the Plus model, focusing on sleek ergonomics and lightweight titanium-aluminum chassis.',
    ram: 12,
    storage: 256,
    screenSize: 6.6,
    processor: 'Apple A19 Pro',
    color: 'Sky Blue',
    os: 'iOS',
    releaseYear: 2025,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 3100,
      refreshRate: 120,
      mainCameraMp: 48,
      frontCameraMp: 24,
      bodyMaterial: 'Titanium / Aluminum',
      simFormat: 'eSIM Only',
    },
  },

  // ==================== SAMSUNG (7 моделей) ====================
  {
    name: 'Samsung Galaxy A55 5G',
    category: Category.SMARTPHONE,
    brand: 'Samsung',
    price: 449.99,
    stockQuantity: 60,
    images: ['https://images.unsplash.com/photo-1583573636246-18cb2246697f'],
    description:
      'Mid-range champ with a metal frame, 6.6-inch FHD+ Super AMOLED 120Hz display, and Samsung Knox Vault security.',
    ram: 8,
    storage: 128,
    screenSize: 6.6,
    processor: 'Exynos 1480',
    color: 'Awesome Iceblue',
    os: 'Android',
    releaseYear: 2024,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 5000,
      refreshRate: 120,
      mainCameraMp: 50,
      frontCameraMp: 32,
      bodyMaterial: 'Glass / Aluminum',
      simFormat: 'Dual SIM',
    },
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    category: Category.SMARTPHONE,
    brand: 'Samsung',
    price: 1299.99,
    stockQuantity: 25,
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf'],
    description:
      'Built with Galaxy AI, a flat 6.8-inch QHD+ AMOLED display, Titanium frame, integrated S Pen, and 200MP Quad Telephoto camera.',
    ram: 12,
    storage: 512,
    screenSize: 6.8,
    processor: 'Qualcomm Snapdragon 8 Gen 3',
    color: 'Titanium Gray',
    os: 'Android',
    releaseYear: 2024,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 5000,
      refreshRate: 120,
      mainCameraMp: 200,
      frontCameraMp: 12,
      bodyMaterial: 'Titanium',
      simFormat: 'Dual SIM + eSIM',
      hasStylus: true,
    },
  },
  {
    name: 'Samsung Galaxy Z Fold 6',
    category: Category.SMARTPHONE,
    brand: 'Samsung',
    price: 1899.99,
    stockQuantity: 12,
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf'],
    description:
      'Sleeker foldable design with Dual-Rail hinge, Snapdragon 8 Gen 3 for Galaxy, and full Galaxy AI multitasking tools.',
    ram: 12,
    storage: 512,
    screenSize: 7.6,
    processor: 'Qualcomm Snapdragon 8 Gen 3',
    color: 'Navy',
    os: 'Android',
    releaseYear: 2024,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 4400,
      refreshRate: 120,
      mainCameraMp: 50,
      frontCameraMp: 10,
      bodyMaterial: 'Armor Aluminum',
      simFormat: 'Dual SIM + eSIM',
      hasStylus: true,
    },
  },
  {
    name: 'Samsung Galaxy S25',
    category: Category.SMARTPHONE,
    brand: 'Samsung',
    price: 799.99,
    stockQuantity: 45,
    images: ['https://images.unsplash.com/photo-1583573636246-18cb2246697f'],
    description:
      'Compact flagship with Snapdragon 8 Elite, improved cooling, 12GB base RAM, and enhanced Galaxy AI capabilities.',
    ram: 12,
    storage: 256,
    screenSize: 6.2,
    processor: 'Qualcomm Snapdragon 8 Elite',
    color: 'Icy Blue',
    os: 'Android',
    releaseYear: 2025,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 4000,
      refreshRate: 120,
      mainCameraMp: 50,
      frontCameraMp: 12,
      bodyMaterial: 'Armor Aluminum',
      simFormat: 'Dual SIM + eSIM',
    },
  },
  {
    name: 'Samsung Galaxy S25 Ultra',
    category: Category.SMARTPHONE,
    brand: 'Samsung',
    price: 1299.99,
    stockQuantity: 40,
    images: ['https://images.unsplash.com/photo-1583573636246-18cb2246697f'],
    description:
      'Features rounded ergonomic corners, Snapdragon 8 Elite SoC, 16GB RAM for local AI models, and upgraded 50MP Ultrawide lens.',
    ram: 16,
    storage: 512,
    screenSize: 6.86,
    processor: 'Qualcomm Snapdragon 8 Elite',
    color: 'Titanium Silver',
    os: 'Android',
    releaseYear: 2025,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 5000,
      refreshRate: 120,
      mainCameraMp: 200,
      frontCameraMp: 12,
      bodyMaterial: 'Titanium',
      simFormat: 'Dual SIM + eSIM',
      hasStylus: true,
    },
  },
  {
    name: 'Samsung Galaxy A56 5G',
    category: Category.SMARTPHONE,
    brand: 'Samsung',
    price: 479.99,
    stockQuantity: 50,
    images: ['https://images.unsplash.com/photo-1583573636246-18cb2246697f'],
    description:
      'Popular mid-ranger upgraded with Exynos 1580, faster 45W charging, and flagship-grade camera algorithms.',
    ram: 8,
    storage: 256,
    screenSize: 6.6,
    processor: 'Exynos 1580',
    color: 'Awesome Lime',
    os: 'Android',
    releaseYear: 2025,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 5000,
      refreshRate: 120,
      mainCameraMp: 50,
      frontCameraMp: 12,
      bodyMaterial: 'Glass / Aluminum',
      simFormat: 'Dual SIM',
    },
  },
  {
    name: 'Samsung Galaxy S26 Ultra',
    category: Category.SMARTPHONE,
    brand: 'Samsung',
    price: 1399.99,
    stockQuantity: 15,
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf'],
    description:
      'Next-gen AI flagship powered by Snapdragon 8 Gen 5, featuring a refined anti-reflective display and upgraded thermal cooling.',
    ram: 16,
    storage: 1024,
    screenSize: 6.9,
    processor: 'Qualcomm Snapdragon 8 Gen 5',
    color: 'Phantom Black',
    os: 'Android',
    releaseYear: 2026,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 5200,
      refreshRate: 144,
      mainCameraMp: 200,
      frontCameraMp: 24,
      bodyMaterial: 'Titanium Alloy',
      simFormat: 'Dual SIM + eSIM',
      hasStylus: true,
    },
  },

  // ==================== XIAOMI (6 моделей) ====================
  {
    name: 'Xiaomi 14 Ultra',
    category: Category.SMARTPHONE,
    brand: 'Xiaomi',
    price: 1399.99,
    stockQuantity: 18,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9'],
    description:
      'Co-engineered with Leica, featuring quad-camera system with 1-inch Sony LYT-900 sensor and stepless variable aperture.',
    ram: 16,
    storage: 512,
    screenSize: 6.73,
    processor: 'Qualcomm Snapdragon 8 Gen 3',
    color: 'Black',
    os: 'Android',
    releaseYear: 2024,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 5000,
      refreshRate: 120,
      mainCameraMp: 50,
      frontCameraMp: 32,
      bodyMaterial: 'Eco Leather / Aluminum',
      simFormat: 'Dual SIM',
    },
  },
  {
    name: 'Poco X6 Pro',
    category: Category.SMARTPHONE,
    brand: 'Xiaomi',
    price: 329.99,
    stockQuantity: 50,
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97'],
    description:
      'Performance beast for budget gaming featuring Dimensity 8300-Ultra, CrystalRes 120Hz Flow AMOLED, and 67W Turbo Charging.',
    ram: 12,
    storage: 512,
    screenSize: 6.67,
    processor: 'MediaTek Dimensity 8300-Ultra',
    color: 'Yellow',
    os: 'Android',
    releaseYear: 2024,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 5000,
      refreshRate: 120,
      mainCameraMp: 64,
      frontCameraMp: 16,
      bodyMaterial: 'Eco Leather / Plastic',
      simFormat: 'Dual SIM',
    },
  },
  {
    name: 'Xiaomi 15 Pro',
    category: Category.SMARTPHONE,
    brand: 'Xiaomi',
    price: 999.99,
    stockQuantity: 20,
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97'],
    description:
      'Packed with massive 6100mAh Silicon-Carbon battery, Snapdragon 8 Elite processor, and Leica Summilux optical lenses.',
    ram: 16,
    storage: 512,
    screenSize: 6.73,
    processor: 'Qualcomm Snapdragon 8 Elite',
    color: 'Liquid Silver',
    os: 'Android',
    releaseYear: 2025,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 6100,
      refreshRate: 120,
      mainCameraMp: 50,
      frontCameraMp: 32,
      bodyMaterial: 'Glass / Aluminum',
      simFormat: 'Dual SIM',
    },
  },
  {
    name: 'Poco X7 Pro',
    category: Category.SMARTPHONE,
    brand: 'Xiaomi',
    price: 369.99,
    stockQuantity: 40,
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97'],
    description:
      'Mid-range performance phone featuring Dimensity 8400 SoC, HyperOS 2.0, 90W fast charging, and slim bezel AMOLED.',
    ram: 12,
    storage: 512,
    screenSize: 6.67,
    processor: 'MediaTek Dimensity 8400',
    color: 'Black / Yellow',
    os: 'Android',
    releaseYear: 2025,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 5500,
      refreshRate: 120,
      mainCameraMp: 50,
      frontCameraMp: 20,
      bodyMaterial: 'Plastic / Glass',
      simFormat: 'Dual SIM',
    },
  },
  {
    name: 'Xiaomi 16 Ultra',
    category: Category.SMARTPHONE,
    brand: 'Xiaomi',
    price: 1449.99,
    stockQuantity: 10,
    images: ['https://images.unsplash.com/photo-1546054454-aa26e2b734c7'],
    description:
      'Photography powerhouse featuring 200MP periscope telephoto camera and HyperOS 3.0 ultra-fluid interface.',
    ram: 16,
    storage: 512,
    screenSize: 6.8,
    processor: 'Qualcomm Snapdragon 8 Gen 5',
    color: 'Ceramic White',
    os: 'Android',
    releaseYear: 2026,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 6300,
      refreshRate: 144,
      mainCameraMp: 50,
      frontCameraMp: 32,
      bodyMaterial: 'Ceramic',
      simFormat: 'Dual SIM',
    },
  },
  {
    name: 'Xiaomi Redmi Note 15 Pro 5G',
    category: Category.SMARTPHONE,
    brand: 'Xiaomi',
    price: 399.99,
    stockQuantity: 55,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9'],
    description:
      'Bestselling mid-ranger featuring 200MP main camera with OIS, IP68 water resistance, and 6500mAh high-density battery.',
    ram: 12,
    storage: 256,
    screenSize: 6.67,
    processor: 'MediaTek Dimensity 7400',
    color: 'Ocean Blue',
    os: 'Android',
    releaseYear: 2026,
    has5G: true,
    hasNfc: true,
    attributes: {
      batteryCapacity: 6500,
      refreshRate: 120,
      mainCameraMp: 200,
      frontCameraMp: 32,
      bodyMaterial: 'Glass / Plastic',
      simFormat: 'Dual SIM',
    },
  },
];

export default smartphones;
